stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.8.4-amazoncorretto-8
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: haoger/rpd:v1
      pushRemote: true
      registry: 127.0.0.1:34078
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
