stages:
- name: compile
  steps:
  - runScriptConfig:
      image: 192.168.167.6:30000/haoger/maven:v1
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: haoger/rpd:v1
      registry: 192.168.167.5:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
